# top level stuff you probably don't need to touch
highlighter: pygments
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: "http://stmarysorthodox.github.io"
baseurl: ""
title: St. Mary's Orthodox Congregation, Santa Cruz
author: St. Mary's Orthodox Congregation, Santa Cruz
description: Church website
avatar: profile.png
email: stmarysorthodoxsc@gmail.com

